### ISSUE TITLE
Install issue - unable to load admin interface

### ISSUE THREAD

**Issue by thelaughingman-1** [KETSE/casebox-vagrant#8]
Hi, I have tried to install casebox with a fresh install of Vagrant and Virtual Box but encounter an error, I have tried using the reload --provision command but get the following output:

```
$vagrant reload --provision
==> default: Attempting graceful shutdown of VM...
==> default: Checking if box 'ubuntu/trusty32' version '20190514.0.0' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 4.3.40
    default: VirtualBox Version: 6.1
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /var/provision => C:/Users/calum/Desktop/casebox/provision
==> default: Running provisioner: shell...
    default: Running: inline script
    default: ================================================================================
    default: Installing common software (ansible, git, nano, wget, curl etc.)...
    default: ================================================================================
    default: [*] Fix name server.
    default: Hit http://security.ubuntu.com trusty-security InRelease
    default: Ign http://archive.ubuntu.com trusty InRelease
    default: Hit http://archive.ubuntu.com trusty-updates InRelease
    default: Hit http://security.ubuntu.com trusty-security/main Sources
    default: Hit http://archive.ubuntu.com trusty-backports InRelease
    default: Hit http://archive.ubuntu.com trusty Release.gpg
    default: Hit http://archive.ubuntu.com trusty-updates/main Sources
    default: Hit http://security.ubuntu.com trusty-security/universe Sources
    default: Hit http://archive.ubuntu.com trusty-updates/restricted Sources
    default: Hit http://security.ubuntu.com trusty-security/main i386 Packages
    default: Hit http://archive.ubuntu.com trusty-updates/universe Sources
    default: Hit http://security.ubuntu.com trusty-security/universe i386 Packages
    default: Hit http://archive.ubuntu.com trusty-updates/multiverse Sources
    default: Hit http://security.ubuntu.com trusty-security/main Translation-en
    default: Hit http://archive.ubuntu.com trusty-updates/main i386 Packages
    default: Hit http://security.ubuntu.com trusty-security/universe Translation-en
    default: Hit http://archive.ubuntu.com trusty-updates/restricted i386 Packages
    default: Hit http://archive.ubuntu.com trusty-updates/universe i386 Packages
    default: Hit http://archive.ubuntu.com trusty-updates/multiverse i386 Packages
    default: Hit http://archive.ubuntu.com trusty-updates/main Translation-en
    default: Hit http://archive.ubuntu.com trusty-updates/multiverse Translation-en
    default: Hit http://archive.ubuntu.com trusty-updates/restricted Translation-en
    default: Hit http://archive.ubuntu.com trusty-updates/universe Translation-en
    default: Hit http://archive.ubuntu.com trusty Release
    default: Hit http://archive.ubuntu.com trusty-backports/main Sources
    default: Hit http://archive.ubuntu.com trusty-backports/restricted Sources
    default: Hit http://archive.ubuntu.com trusty-backports/universe Sources
    default: Hit http://archive.ubuntu.com trusty-backports/multiverse Sources
    default: Hit http://archive.ubuntu.com trusty-backports/main i386 Packages
    default: Hit http://archive.ubuntu.com trusty-backports/restricted i386 Packages
    default: Hit http://archive.ubuntu.com trusty-backports/universe i386 Packages
    default: Hit http://archive.ubuntu.com trusty-backports/multiverse i386 Packages
    default: Hit http://archive.ubuntu.com trusty-backports/main Translation-en
    default: Hit http://archive.ubuntu.com trusty-backports/multiverse Translation-en
    default: Hit http://archive.ubuntu.com trusty-backports/restricted Translation-en
    default: Hit http://archive.ubuntu.com trusty-backports/universe Translation-en
    default: Get:1 https://esm.ubuntu.com trusty-infra-security InRelease
    default: Hit http://archive.ubuntu.com trusty/main Sources
    default: Hit http://archive.ubuntu.com trusty/restricted Sources
    default: Hit http://archive.ubuntu.com trusty/universe Sources
    default: Hit http://archive.ubuntu.com trusty/multiverse Sources
    default: Get:2 https://esm.ubuntu.com trusty-infra-updates InRelease
    default: Hit http://archive.ubuntu.com trusty/main i386 Packages
    default: Hit http://archive.ubuntu.com trusty/restricted i386 Packages
    default: Hit http://archive.ubuntu.com trusty/universe i386 Packages
    default: Hit https://esm.ubuntu.com trusty-infra-security/main i386 Packages
    default: Hit http://archive.ubuntu.com trusty/multiverse i386 Packages
    default: Hit http://archive.ubuntu.com trusty/main Translation-en
    default: Get:3 https://esm.ubuntu.com trusty-infra-security/main Translation-en_US
    default: Hit http://archive.ubuntu.com trusty/multiverse Translation-en
    default: Hit http://archive.ubuntu.com trusty/restricted Translation-en
    default: Hit http://archive.ubuntu.com trusty/universe Translation-en
    default: Hit https://esm.ubuntu.com trusty-infra-updates/main i386 Packages
    default: Get:4 https://esm.ubuntu.com trusty-infra-updates/main Translation-en_US
    default: Ign http://archive.ubuntu.com trusty/main Translation-en_US
    default: Ign http://archive.ubuntu.com trusty/multiverse Translation-en_US
    default: Ign http://archive.ubuntu.com trusty/restricted Translation-en_US
    default: Ign http://archive.ubuntu.com trusty/universe Translation-en_US
    default: Ign https://esm.ubuntu.com trusty-infra-security/main Translation-en_US
    default: Ign https://esm.ubuntu.com trusty-infra-security/main Translation-en
    default: Ign https://esm.ubuntu.com trusty-infra-updates/main Translation-en_US
    default: Ign https://esm.ubuntu.com trusty-infra-updates/main Translation-en
    default: Fetched 14.9 kB in 6s (2,169 B/s)
    default: Reading package lists...
    default: [*] Install python-pip, python-dev, git, curl, wget, nano.
    default: Reading package lists...
    default: Building dependency tree...
    default: Reading state information...
    default: build-essential is already the newest version.
    default: nano is already the newest version.
    default: python-dev is already the newest version.
    default: curl is already the newest version.
    default: git is already the newest version.
    default: libffi-dev is already the newest version.
    default: libssl-dev is already the newest version.
    default: wget is already the newest version.
    default: python-pip is already the newest version.
    default: 0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
    default: Downloading/unpacking setuptools from https://files.pythonhosted.org/packages/95/fe/2687907be1d6291a84a9b51220595a4f89d9477032c57f21e7c633465540/setuptools-47.3.1.zip#sha256=843037738d1e34e8b326b5e061f474aca6ef9d7ece41329afbc8aac6195a3920
    default:   Running setup.py (path:/tmp/pip_build_root/setuptools/setup.py) egg_info for package setuptools
    default:     pkg_resources/py2_warn.py:15: UserWarning: Setuptools no longer works on Python 2
    default:     ************************************************************
    default:     Encountered a version of Setuptools that no longer supports
    default:     this version of Python. Please head to
    default:     https://bit.ly/setuptools-py2-sunset for support.
    default:     ************************************************************
    default:       warnings.warn(pre + "*" * 60 + msg + "*" * 60)
    default:     Complete output from command python setup.py egg_info:
    default:     pkg_resources/py2_warn.py:15: UserWarning: Setuptools no longer works on Python 2
    default:
    default: ************************************************************
    default:
    default: Encountered a version of Setuptools that no longer supports
    default:
    default: this version of Python. Please head to
    default:
    default: https://bit.ly/setuptools-py2-sunset for support.
    default:
    default: ************************************************************
    default:
    default:   warnings.warn(pre + "*" * 60 + msg + "*" * 60)
    default:
    default: ----------------------------------------
    default: Cleaning up...
    default: Command python setup.py egg_info failed with error code 32 in /tmp/pip_build_root/setuptools
    default: Storing debug log for failure in /root/.pip/pip.log
    default: [*] Install markupsafe.
    default: Requirement already satisfied (use --upgrade to upgrade): markupsafe in /usr/local/lib/python2.7/dist-packages
    default: Cleaning up...
    default: [*] Install ansible.
    default: Downloading/unpacking ansible
    default:   Running setup.py (path:/tmp/pip_build_root/ansible/setup.py) egg_info for package ansible
    default:
    default:     warning: no previously-included files found matching 'docs/docsite/rst_warnings'
    default:     warning: no previously-included files matching '*' found under directory 'docs/docsite/_build'
    default:     warning: no previously-included files matching '*.pyc' found under directory 'docs/docsite/_extensions'
    default:     warning: no previously-included files matching '*.pyo' found under directory 'docs/docsite/_extensions'
    default:     warning: no previously-included files found matching 'test/sanity/code-smell/botmeta.*'
    default: Downloading/unpacking jinja2 (from ansible)
    default: Requirement already satisfied (use --upgrade to upgrade): PyYAML in /usr/lib/python2.7/dist-packages (from ansible)
    default: Downloading/unpacking cryptography (from ansible)
    default:   Running setup.py (path:/tmp/pip_build_root/cryptography/setup.py) egg_info for package cryptography
    default:     Traceback (most recent call last):
    default:       File "<string>", line 17, in <module>
    default:       File "/tmp/pip_build_root/cryptography/setup.py", line 26, in <module>
    default:         "cryptography requires setuptools 18.5 or newer, please upgrade to a "
    default:     RuntimeError: cryptography requires setuptools 18.5 or newer, please upgrade to a newer version of setuptools
    default:     Complete output from command python setup.py egg_info:
    default:     Traceback (most recent call last):
    default:
    default:   File "<string>", line 17, in <module>
    default:
    default:   File "/tmp/pip_build_root/cryptography/setup.py", line 26, in <module>
    default:
    default:     "cryptography requires setuptools 18.5 or newer, please upgrade to a "
    default:
    default: RuntimeError: cryptography requires setuptools 18.5 or newer, please upgrade to a newer version of setuptools
    default:
    default: ----------------------------------------
    default: Cleaning up...
    default: Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/cryptography
    default: Storing debug log for failure in /root/.pip/pip.log
    default: [*] Autoremove unused software .
    default: Reading package lists...
    default: Building dependency tree...
    default: Reading state information...
    default: 0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
    default: [x] Done.
==> default: Running provisioner: shell...
    default: Running: inline script
    default: ================================================================================
    default: Installing (core software) Nginx, PHP, MySQL, LibreOffice etc...
    default: ================================================================================
    default: /tmp/vagrant-shell: line 4: ansible-playbook: command not found
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

```

Any ideas on how to get this working?

**Comment by hewcb** [comment]
same issue. any solution?
